// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Mon Sep 12 19:11:20 2016

key_matrix_4x4 key_matrix_4x4_inst
(
	.clk_1mhz(clk_1mhz_sig) ,	// input  clk_1mhz_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.key_in(key_in_sig) ,	// input [3:0] key_in_sig
	.key_out(key_out_sig) ,	// output [3:0] key_out_sig
	.irq_key(irq_key_sig) ,	// output  irq_key_sig
	.key_code_out(key_code_out_sig) 	// output [7:0] key_code_out_sig
);

